[project]
name = "dev-box-setup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible>=12.1.0",
    "ansible-lint>=25.9.2",
    "distro>=1.9.0",
]
